# Generated by Django 4.2.3 on 2026-02-03 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BiljniDodatak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naziv_proizvoda", models.CharField(max_length=255)),
                (
                    "farmaceutski_oblik",
                    models.CharField(
                        choices=[
                            ("kapsule", "Kapsule"),
                            ("tablete", "Tablete"),
                            ("prah", "Prah"),
                            ("čaj", "Čaj"),
                            ("granule", "Granule"),
                            ("sirup", "Sirup"),
                            ("kapi", "Kapi"),
                            ("tinktura", "Tinktura"),
                            ("ulje", "Ulje"),
                            ("pastile", "Pastile"),
                        ],
                        max_length=50,
                    ),
                ),
                ("neto_kolicina", models.FloatField()),
                (
                    "jedinica_kolicina",
                    models.CharField(
                        choices=[
                            ("g", "g"),
                            ("mg", "mg"),
                            ("ml", "ml"),
                            ("µg", "µg"),
                            ("kapsula", "kapsula"),
                            ("tableta", "tableta"),
                            ("vrećica", "vrećica"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tip_ambalaze",
                    models.CharField(
                        choices=[
                            ("bocica", "Bočica"),
                            ("blister", "Blister"),
                            ("vrećica", "Vrećica"),
                            ("pakiranje_caj", "Pakovanje za čaj"),
                            ("tubica", "Tubica"),
                            ("teglica", "Teglica"),
                            ("ampula", "Ampula"),
                            ("sprica", "Šprica / kapi"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "materijal_ambalaze",
                    models.CharField(
                        choices=[
                            ("plastika", "Plastika"),
                            ("staklo", "Staklo"),
                            ("aluminij", "Aluminijum"),
                            ("papir", "Papir / Karton"),
                            ("metal", "Metal"),
                        ],
                        max_length=50,
                    ),
                ),
                ("zastita_svjetlost", models.BooleanField(default=False)),
                ("temp_min", models.IntegerField(blank=True, null=True)),
                ("temp_max", models.IntegerField(blank=True, null=True)),
                ("namjena", models.CharField(max_length=255)),
                ("doza", models.FloatField(blank=True, null=True)),
                (
                    "jedinica_doza",
                    models.CharField(
                        choices=[
                            ("kapsula", "Kapsula"),
                            ("tableta", "Tableta"),
                            ("ml", "ml"),
                            ("kasika", "Kašika"),
                            ("kasicica", "Kašičica"),
                            ("vrecica", "Vrećica"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nacin_primjene",
                    models.CharField(
                        choices=[
                            ("oralno", "Oralno"),
                            ("sublingvalno", "Sublingvalno"),
                            ("lokalno", "Lokalno"),
                            ("inhalacija", "Inhalacija"),
                        ],
                        max_length=50,
                    ),
                ),
                ("kontra_djeca", models.BooleanField(default=False)),
                ("kontra_trudnice", models.BooleanField(default=False)),
                ("kontra_dojilje", models.BooleanField(default=False)),
                ("kontra_hronicni", models.BooleanField(default=False)),
                ("oprez_djecu", models.BooleanField(default=False)),
                ("oprez_doziranje", models.BooleanField(default=False)),
                ("oprez_alergije", models.BooleanField(default=False)),
                ("oprez_trudnice", models.BooleanField(default=False)),
                ("oprez_dojilje", models.BooleanField(default=False)),
                ("oprez_lekovi", models.BooleanField(default=False)),
                (
                    "bse",
                    models.BooleanField(default=False, verbose_name="BSE/TSE free"),
                ),
                ("gmo", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="BiljnaDroga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naziv_sr", models.CharField(max_length=255)),
                ("latinski_naziv", models.CharField(max_length=255)),
                (
                    "dio_biljke",
                    models.CharField(
                        choices=[
                            ("korijen", "Korijen"),
                            ("rizom", "Rizom"),
                            ("list", "List"),
                            ("cvijet", "Cvijet"),
                            ("plod", "Plod"),
                            ("sjeme", "Sjeme"),
                            ("kora", "Kora"),
                            ("herba", "Herba"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priprema",
                    models.CharField(
                        choices=[
                            ("svjeza", "Svježa"),
                            ("osusena", "Osušena"),
                            ("fermentisana", "Fermentisana"),
                            ("preradjena", "Prerađena / ekstrakt"),
                            ("prah", "Prah"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "rastvarac",
                    models.CharField(
                        choices=[
                            ("voda", "Voda"),
                            ("etanol_70", "70% Etanol"),
                            ("aceton", "Aceton"),
                            ("glicerin", "Glicerin"),
                            ("propilen_glikol", "Propilen glikol"),
                        ],
                        max_length=50,
                    ),
                ),
                ("standardizacija_proc", models.FloatField(blank=True, null=True)),
                (
                    "standardizacija_supstanca",
                    models.CharField(blank=True, max_length=100),
                ),
                ("zemlja_porijekla", models.CharField(blank=True, max_length=50)),
                ("kolicina", models.FloatField(blank=True, null=True)),
                (
                    "jedinica_kolicina",
                    models.CharField(
                        choices=[("mg", "mg"), ("g", "g"), ("%", "%"), ("ml", "ml")],
                        max_length=20,
                    ),
                ),
                (
                    "dodatak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biljne_droge",
                        to="preparat.biljnidodatak",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AktivnaSupstanca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naziv", models.CharField(max_length=255)),
                ("hemijski_oblik", models.CharField(max_length=255)),
                ("kolicina", models.FloatField(blank=True, null=True)),
                (
                    "jedinica",
                    models.CharField(
                        choices=[
                            ("mg", "mg"),
                            ("µg", "µg"),
                            ("g", "g"),
                            ("ml", "ml"),
                            ("IU", "IU"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "porijeklo",
                    models.CharField(
                        choices=[
                            ("biljna", "Iz biljne droge"),
                            ("sintetska", "Sintetska / dodana"),
                            ("mineralna", "Mineralna"),
                            ("animalna", "Animalna"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "dodatak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aktivne_supstance",
                        to="preparat.biljnidodatak",
                    ),
                ),
            ],
        ),
    ]
