# Generated by Django 4.2.3 on 2026-02-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("preparat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="biljnadroga", name="dodatak",),
        migrations.DeleteModel(name="AktivnaSupstanca",),
        migrations.DeleteModel(name="BiljnaDroga",),
        migrations.DeleteModel(name="BiljniDodatak",),
    ]
