# Generated by Django 4.2.3 on 2026-02-11 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "preparat",
            "0002_remove_biljnadroga_dodatak_delete_aktivnasupstanca_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BiljniDodatak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naziv", models.CharField(max_length=255)),
                (
                    "oblik",
                    models.CharField(
                        choices=[
                            ("tablete", "Tablete"),
                            ("kapsule", "Kapsule"),
                            ("prah", "Prah"),
                            ("granule", "Granule"),
                            ("pastile", "Pastile"),
                            ("mast", "Mast"),
                            ("gel", "Gel"),
                            ("krem", "Krem"),
                            ("sirup", "Sirup"),
                            ("oralni_rastvor", "Oralni rastvor"),
                            ("kapi", "Kapi"),
                            ("tinktura", "Tinktura"),
                            ("sprej", "Sprej"),
                            ("ulje", "Ulje"),
                            ("caj", "Čaj"),
                        ],
                        max_length=50,
                    ),
                ),
                ("neto_kolicina", models.FloatField(blank=True, null=True)),
                (
                    "jedinica_kolicina",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("g", "g"),
                            ("mg", "mg"),
                            ("ml", "ml"),
                            ("µg", "µg"),
                            ("kapsula", "kapsula"),
                            ("tableta", "tableta"),
                            ("vrecica", "vrećica"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "tip_ambalaze",
                    models.CharField(
                        choices=[
                            ("bocica", "Bočica"),
                            ("blister", "Blister"),
                            ("vrecica", "Vrećica"),
                            ("pakiranje_caj", "Pakovanje za čaj"),
                            ("tubica", "Tubica"),
                            ("teglica", "Teglica"),
                            ("kartonska_kutija", "Kartonska kutija"),
                            ("bocica_kapaljka", "Bočica sa kapaljkom"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "materijal_ambalaze",
                    models.CharField(
                        choices=[
                            ("plastika", "Plastika"),
                            ("staklo", "Staklo"),
                            ("aluminij", "Aluminijum"),
                            ("papir", "Papir / Karton"),
                            ("metal", "Metal"),
                        ],
                        max_length=50,
                    ),
                ),
                ("zastita_svjetlost", models.BooleanField(default=False)),
                ("zastita_vlaga", models.BooleanField(default=False)),
                ("temp_min", models.IntegerField(blank=True, null=True)),
                ("temp_max", models.IntegerField(blank=True, null=True)),
                (
                    "namena",
                    models.CharField(
                        choices=[
                            ("poboljsava_imunitet", "Poboljšava imunitet"),
                            ("poboljsava_probavu", "Poboljšava probavu"),
                            ("zdravlje_kose_koze", "Zdravlje kose / kože / noktiju"),
                            ("poboljsava_kosti", "Poboljšava zdravlje kostiju"),
                            ("smanjuje_umor", "Smanjuje umor"),
                            ("poboljsava_cirkulaciju", "Poboljšava cirkulaciju"),
                            ("podrzava_jetru", "Podrška funkciji jetre"),
                            ("poboljsava_snovi", "Poboljšava san"),
                            ("opste_zdravlje", "Opšte zdravlje"),
                            ("poboljsava_imunitet_probavu", "Imunitet + probava"),
                        ],
                        max_length=100,
                    ),
                ),
                ("doza", models.FloatField(blank=True, null=True)),
                (
                    "jedinica_doza",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("kapsula", "Kapsula"),
                            ("tableta", "Tableta"),
                            ("ml", "ml"),
                            ("kasika", "Kašika"),
                            ("kasicica", "Kašičica"),
                            ("vrecica", "Vrećica"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "nacin_uzimanja",
                    models.CharField(
                        choices=[
                            ("oralno", "Oralno"),
                            ("sublingvalno", "Sublingvalno"),
                            ("lokalno", "Lokalno"),
                            ("inhalacija", "Inhalacija"),
                        ],
                        max_length=50,
                    ),
                ),
                ("ogranicenja_djeca", models.BooleanField(default=False)),
                ("ogranicenja_trudnice", models.BooleanField(default=False)),
                ("ogranicenja_dojilje", models.BooleanField(default=False)),
                ("ogranicenja_hronicni", models.BooleanField(default=False)),
                ("mjera_djeca", models.BooleanField(default=False)),
                ("mjera_doziranje", models.BooleanField(default=False)),
                ("mjera_zamjena", models.BooleanField(default=False)),
                ("mjera_obrok", models.BooleanField(default=False)),
                ("mjera_skladistenje", models.BooleanField(default=False)),
                ("upozorenje_alergije", models.BooleanField(default=False)),
                ("upozorenje_lijekovi", models.BooleanField(default=False)),
                ("upozorenje_gi", models.BooleanField(default=False)),
                ("upozorenje_pritisak", models.BooleanField(default=False)),
                ("upozorenje_secer", models.BooleanField(default=False)),
                (
                    "bse_status",
                    models.CharField(
                        choices=[
                            ("nije_potrebno", "Nije potrebno"),
                            ("prilozeno", "Priloženo"),
                        ],
                        default="nije_potrebno",
                        max_length=20,
                    ),
                ),
                ("bse_napomena", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Studija",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naziv", models.CharField(max_length=255)),
                (
                    "tip",
                    models.CharField(
                        choices=[
                            ("klinicko", "Kliničko"),
                            ("laboratorijsko", "Laboratorijsko / pre-kliničko"),
                            ("literatura", "Literatura / review"),
                        ],
                        max_length=50,
                    ),
                ),
                ("godina", models.CharField(blank=True, max_length=100)),
                ("doi", models.CharField(blank=True, max_length=100)),
                (
                    "dodatak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studije",
                        to="preparat.biljnidodatak",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BiljnaDroga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("biljka_sr", models.CharField(max_length=255)),
                ("biljka_lat", models.CharField(max_length=255)),
                (
                    "dio_biljke",
                    models.CharField(
                        choices=[
                            ("korijen", "Korijen"),
                            ("rizom", "Rizom"),
                            ("list", "List"),
                            ("cvijet", "Cvijet"),
                            ("plod", "Plod"),
                            ("sjeme", "Sjeme"),
                            ("kora", "Kora"),
                            ("herba", "Herba"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "stanje_biljke",
                    models.CharField(
                        choices=[
                            ("svjeza", "Svježa"),
                            ("osusena", "Osušena"),
                            ("fermentisana", "Fermentisana"),
                            ("preradjena", "Prerađena / ekstrakt"),
                            ("prah", "Prah"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "rastvarac",
                    models.CharField(
                        choices=[
                            ("voda", "Voda"),
                            ("etanol_70", "70% Etanol"),
                            ("metanol", "Metanol"),
                            ("aceton", "Aceton"),
                            ("glicerol", "Glicerol"),
                            ("propilen_glikol", "Propilen glikol"),
                        ],
                        max_length=50,
                    ),
                ),
                ("der", models.CharField(blank=True, max_length=50)),
                ("standardizacija_proc", models.FloatField(blank=True, null=True)),
                (
                    "standardizacija_supstanca",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "zemlja_porijekla",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("srbija", "Srbija"),
                            ("bih", "Bosna i Hercegovina"),
                            ("eu", "EU"),
                        ],
                        max_length=50,
                    ),
                ),
                ("kolicina_biljna", models.FloatField(blank=True, null=True)),
                (
                    "jedinica_biljna",
                    models.CharField(
                        blank=True,
                        choices=[("mg", "mg"), ("g", "g"), ("ml", "ml"), ("%", "%")],
                        max_length=20,
                    ),
                ),
                (
                    "dodatak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biljne_droge",
                        to="preparat.biljnidodatak",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AktivnaSupstanca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naziv", models.CharField(max_length=255)),
                ("hemijski_oblik", models.CharField(blank=True, max_length=255)),
                ("kolicina", models.FloatField(blank=True, null=True)),
                (
                    "jedinica",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mg", "mg"),
                            ("µg", "µg"),
                            ("g", "g"),
                            ("ml", "ml"),
                            ("IU", "IU"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "porijeklo",
                    models.CharField(
                        choices=[
                            ("biljna", "Iz biljne droge"),
                            ("sintetska", "Sintetska"),
                            ("mineralna", "Mineralna"),
                            ("animalna", "Animalna"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "dodatak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aktivne_supstance",
                        to="preparat.biljnidodatak",
                    ),
                ),
            ],
        ),
    ]
