# Generated by Django 4.2.3 on 2026-02-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preparat", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biljnidodatak",
            name="namena",
            field=models.CharField(
                choices=[
                    ("poboljsava_imunitet", "Poboljšava imunitet"),
                    ("poboljsava_probavu", "Poboljšava probavu"),
                    ("zdravlje_kose_koze", "Zdravlje kose / kože / noktiju"),
                    ("poboljsava_kosti", "Poboljšava zdravlje kostiju"),
                    ("smanjuje_umor", "Smanjuje umor"),
                    ("poboljsava_cirkulaciju", "Poboljšava cirkulaciju"),
                    ("podrzava_jetru", "Podrška funkciji jetre"),
                    ("poboljsava_snovi", "Poboljšava san"),
                    ("opste_zdravlje", "Opšte zdravlje"),
                    ("poboljsava_imunitet_probavu", "Imunitet + probava"),
                    (
                        "podržava normalan nivo hemoglobina",
                        "Podržava normalan nivo hemoglobina",
                    ),
                ],
                max_length=100,
            ),
        ),
    ]
