# Generated by Django 4.2.3 on 2026-02-12 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("preparat", "0004_alter_biljnidodatak_namena"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biljnadroga",
            name="standardizacija_supstanca",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="standardizovane_droge",
                to="preparat.aktivnasupstanca",
            ),
        ),
    ]
