# Generated by Django 4.2.3 on 2026-02-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preparat", "0005_alter_biljnadroga_standardizacija_supstanca"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biljnidodatak",
            name="naziv",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
