# Generated by Django 4.2.3 on 2026-02-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparat', '0006_alter_biljnidodatak_naziv'),
    ]

    operations = [
        migrations.AddField(
            model_name='biljnidodatak',
            name='maksimalna_dnevna_doza',
            field=models.FloatField(default=15),
            preserve_default=False,
        ),
    ]
